import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import Header from "./components/Header";
import Travelslide from "./components/Travelslide";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        {children}
        <Travelslide />
      </body>
    </html>
  );
}
